package postgresql

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"github.com/Weit145/Auth_golang/internal/lib/logger"
	"github.com/jackc/pgx/v5"
)

type Storage struct {
	db *pgx.Conn
}

const (
	maxRetries = 5
	retryDelay = 5 * time.Second
)

func New(log *slog.Logger) (*Storage, error) {
	const op = "storage.postgresql.new"
	urlStorage := "postgres://postgres:postgres@localhost:5432/auth_service"

	var conn *pgx.Conn
	var err error

	for i := 0; i < maxRetries; i++ {
		conn, err = pgx.Connect(context.Background(), urlStorage)
		if err == nil {
			break
		}

		log.Warn("Failed to connect to storage, retrying...", slog.Int("attempt", i+1), logger.Err(err))
		time.Sleep(retryDelay)
	}

	if err != nil {
		log.Error("No connect storage", logger.Err(err))
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	if err := migrate(context.Background(), log, conn); err != nil {
		log.Error("Failde migrate", logger.Err(err))
	}

	return &Storage{db: conn}, nil
}

func migrate(ctx context.Context, log *slog.Logger, db *pgx.Conn) error {

	const op = "storage.postgresql.migrate"

	schema := `
	CREATE TABLE auth (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		login TEXT NOT NULL UNIQUE,
		email TEXT NOT NULL UNIQUE,
		password_hash TEXT NOT NULL,

		refresh_token_hash TEXT DEFAULT '0',

		is_active BOOLEAN DEFAULT TRUE,
		is_verified BOOLEAN DEFAULT FALSE,

		role TEXT NOT NULL DEFAULT 'user'
	);
	`

	_, err := db.Exec(ctx, schema)
	if err != nil {
		log.Error("Cannot execute migration", logger.Err(err))
		return fmt.Errorf("%s: cannot execute migration: %w", op, err)
	}

	return nil
}
