package postgresql

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"github.com/Weit145/Auth_golang/internal/domain"
	"github.com/Weit145/Auth_golang/internal/lib/logger"
	"github.com/Weit145/Auth_golang/internal/storage"
	"github.com/Weit145/Auth_golang/internal/storage/postgresql/create"
	"github.com/Weit145/Auth_golang/internal/storage/postgresql/select_user"
	updateverified "github.com/Weit145/Auth_golang/internal/storage/postgresql/update_verified"
	"github.com/jackc/pgx/v5"
)

type Storage struct {
	db  *pgx.Conn
	log *slog.Logger
}

const (
	maxRetries = 5
	retryDelay = 5 * time.Second
)

func New(log *slog.Logger) (*Storage, error) {
	const op = "storage.postgresql.new"
	urlStorage := "postgres://postgres:postgres@postgres:5432/auth_service"

	var conn *pgx.Conn
	var err error

	for i := 0; i < maxRetries; i++ {
		conn, err = pgx.Connect(context.Background(), urlStorage)
		if err == nil {
			break
		}

		log.Warn("Failed to connect to storage, retrying...", slog.Int("attempt", i+1), logger.Err(err))
		time.Sleep(retryDelay)
	}
	if err != nil {
		log.Error("No connect storage", logger.Err(err))
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	if err := migrate(context.Background(), log, conn); err != nil {
		log.Error("Failed to migrate", logger.Err(err))
	}

	return &Storage{
		db:  conn,
		log: log,
	}, nil
}

func (s *Storage) WithTx(ctx context.Context, fn func(tx pgx.Tx) error) error {
	const op = "storage.postgresql.WithTx"

	tx, err := s.db.BeginTx(ctx, pgx.TxOptions{})
	if err != nil {
		return fmt.Errorf("%s: %w", op, err)
	}

	defer func() {
		if r := recover(); r != nil {
			tx.Rollback(ctx)
			panic(r)
		}
	}()

	if err := fn(tx); err != nil {
		if rbErr := tx.Rollback(ctx); rbErr != nil {
			return fmt.Errorf("%s: transaction failed: %w, rollback failed: %v", op, err, rbErr)
		}
		return fmt.Errorf("%s: transaction failed: %w", op, err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("%s: commit failed: %w", op, err)
	}

	return nil
}

func (s *Storage) RegistrationRepo(ctx context.Context, login, email, passwordHash string) error {
	const op = "storage.postgresql.RegistrationRepo"
	return create.CreateUserOp(ctx, s.db, login, email, passwordHash)
}

func (s *Storage) AuthenticateRepo(ctx context.Context, user *domain.User) error {
	const op = "storage.postgresql.AuthenticateRepo"
	retrievedUser, err := select_user.GetUserByLoginOp(ctx, s.db, user.Login)
	if err != nil {
		return fmt.Errorf("%s: %w", op, err)
	}
	*user = *retrievedUser
	return nil
}

func (s *Storage) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	const op = "storage.postgresql.GetUserByEmail"
	user, err := select_user.GetUserByEmailOp(ctx, s.db, email)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}
	return user, nil
}

func (s *Storage) GetUserByLogin(ctx context.Context, login string) (*domain.User, error) {
	const op = "storage.postgresql.GetUserByLogin"
	user, err := select_user.GetUserByLoginOp(ctx, s.db, login)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}
	return user, nil
}

func (s *Storage) UpdateRefreshToken(ctx context.Context, user *domain.User) error {
	const op = "storage.postgresql.UpdateRefreshToken"
	return UpdateRefreshTokenOp(ctx, s.db, user)
}

func (s *Storage) ConfirmRepo(ctx context.Context, user *domain.User) error {
	const op = "storage.postgresql.ConfirmRepo"
	return updateverified.UpdateVerifiedOp(ctx, s.db, user)
}

func UpdateRefreshTokenOp(ctx context.Context, runner storage.QueryRunner, user *domain.User) error {
	const op = "storage.postgresql.UpdateRefreshTokenOp"

	stmt := `UPDATE auth SET refresh_token_hash = $1 WHERE id = $2`
	_, err := runner.Exec(ctx, stmt, user.RefreshTokenHash, user.Id)
	if err != nil {
		return fmt.Errorf("%s: %w", op, err)
	}

	return nil
}

func migrate(ctx context.Context, log *slog.Logger, db *pgx.Conn) error {
	const op = "storage.postgresql.migrate"

	schema := `
	CREATE TABLE IF NOT EXISTS auth (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

		login TEXT NOT NULL UNIQUE,
		email TEXT NOT NULL UNIQUE,
		password_hash TEXT NOT NULL,

		refresh_token_hash TEXT DEFAULT '0',

		is_active BOOLEAN DEFAULT TRUE,
		is_verified BOOLEAN DEFAULT FALSE,

		role TEXT NOT NULL DEFAULT 'user'
	);
	`

	_, err := db.Exec(ctx, schema)
	if err != nil {
		log.Error("Cannot execute migration", logger.Err(err))
		return fmt.Errorf("%s: cannot execute migration: %w", op, err)
	}

	return nil
}
