// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	current "github.com/Weit145/Auth_golang/internal/service/current"
	mock "github.com/stretchr/testify/mock"
)

// ServiceAuth is an autogenerated mock type for the ServiceAuth type
type ServiceAuth struct {
	mock.Mock
}

// Confirm provides a mock function with given fields: ctx, token
func (_m *ServiceAuth) Confirm(ctx context.Context, token string) (string, string, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, token)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// CreateUser provides a mock function with given fields: ctx, login, email, password
func (_m *ServiceAuth) CreateUser(ctx context.Context, login string, email string, password string) error {
	ret := _m.Called(ctx, login, email, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, login, email, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Current provides a mock function with given fields: ctx, AssetToken
func (_m *ServiceAuth) Current(ctx context.Context, AssetToken string) (*current.User, error) {
	ret := _m.Called(ctx, AssetToken)

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 *current.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*current.User, error)); ok {
		return rf(ctx, AssetToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *current.User); ok {
		r0 = rf(ctx, AssetToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*current.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, AssetToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogOutUser provides a mock function with given fields: ctx, AssetToken
func (_m *ServiceAuth) LogOutUser(ctx context.Context, AssetToken string) error {
	ret := _m.Called(ctx, AssetToken)

	if len(ret) == 0 {
		panic("no return value specified for LogOutUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, AssetToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoginUser provides a mock function with given fields: ctx, login, password
func (_m *ServiceAuth) LoginUser(ctx context.Context, login string, password string) (string, string, error) {
	ret := _m.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, string, error)); ok {
		return rf(ctx, login, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, login, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, login, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, login, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Refresh provides a mock function with given fields: ctx, RefreshToken
func (_m *ServiceAuth) Refresh(ctx context.Context, RefreshToken string) (string, error) {
	ret := _m.Called(ctx, RefreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, RefreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, RefreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, RefreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceAuth creates a new instance of ServiceAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceAuth {
	mock := &ServiceAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
